Initialize nixos module system. (translators only)
nix-community/dream2nix pull request #249
Opened 2022-08-12 18:50 UTC by DavHau

This initializes the structure for a potentially fully nixos modules based dream2nix framework.
For now only the translators and some related functionality is migrated as a test to allow for reviews.

In the future, further functionality could/should be migrated to `/src/modules`.

Why we want this?:
  - type checked internal and external interfaces
  - automatically documented interfaces
  - better extensibility of the framework
  - simplify structure of the dream2nix source code

Concerning the file structure:
The idea is that `/src/modules` is a flat structure of directories. It should be easy to find the source of an option definition by knowing the option attribute path.
For example the option `functions.translators.{something}` can be found in `/src/modules/functions.translators`
Every file in `/src/modules/{category}` should contain an `interface.nix` and an `implementation.nix`.
This should make it easy to quickly find the interface definition as a contributor.

Transition phase:
With this now the framework is a mix of nixos-modules and not nixos-modules. That is a bit ugly, but we have no better way other than slowly transitioning to the new structure, and letting both old and new structure access each other.
Currently for the modules

2022-08-14 00:04 UTC, yusdacra requested changes

2022-08-15 13:37 UTC, DavHau commented on src/subsystems/translators.nix
> +  translators = framework.translatorsBySubsystem;
I tried to implement downward compatibility but this got too hacky. It's better to change the extension interface. I added the option `config.modules` (see e654ffaa103d9e08ea8056f66b6ecb301290da1d), updated the examples accordingly and added a notice to the docs.

2022-08-15 19:01 UTC, yusdacra commented on src/subsystems/translators.nix
> +  translators = framework.translatorsBySubsystem;
That's fine too, so I'll mark this as resolved.

2022-08-15 19:05 UTC, yusdacra approved these changes
I'm not sure why the unit tests fail but that should be fixed, other than that it's LGTM

2022-08-16 09:43 UTC, merged