Add wip Haskell example
nix-community/dream2nix pull request #730
Opened 2023-10-11 03:50 UTC by t4ccer

I've been experimenting with dream2nix recently and implemented a simple haskell support via cabal freeze and build plans. Far from being production ready but _maybe_ could be used as a base

Known issues/disclaimers:
- https://github.com/ekmett/free doesn't build because some `sdist` magic is going on and `/doc` dir is moved
- No automatic detection of required c libraries
- Not tested with alternative package registries like https://input-output-hk.github.io/cardano-haskell-packages/
- Tests are not ran
- Dependencies and main projects are built in one derivation so no caching

2023-10-18 23:46 UTC, DavHau requested changes
Very nice work. Would you like to maintain this module in the future?

EDIT: Oh, and sorry for the late review, I've been a bit busy. Will try to be more responsive.

2023-10-18 23:46 UTC, DavHau commented on examples/packages/single-language/haskell-cabal/README.md
> +$ nix run .#checks.x86_64-linux.example-package-haskell-cabal.lock
I really appreciate the effort to add some docs, but these attribute paths are not portable.
Once the example gets copied to another flake, these attribute paths are not guaranteed to be the same.

Maybe remove this file and extend the `./docs` instead by adding a guide (can be separate PR)?

2023-10-30 03:36 UTC, t4ccer commented
Hey, thanks for having a look. I can maintain the Haskell module in my spare time, sure, although I don't have time to actively work on improvements right now, though I'll try addressing some issues in the future

2023-10-30 20:35 UTC, DavHau approved these changes

2023-10-30 20:35 UTC, merged